//CART
export const CART_LOADING_STARTED = 'CART_LOADING_STARTED';
export const CART_LOADING_SUCCESS = 'CART_LOADING_SUCCESS';
export const CART_LOADING_FAILURE = 'CART_LOADING_FAILURE';

export const CART_ADD_STARTED = 'CART_ADD_STARTED';
export const CART_ADD_FAILURE = 'CART_ADD_FAILURE';
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS';
export const CART_DELETE_SUCCESS = 'CART_DELETE_SUCCESS';
export const CART_SCREEN = 'CART_SCREEN';
