// CHECKOUT
export const CHECKOUT_GET_STARTED = 'CHECKOUT_GET_STARTED';
export const CHECKOUT_GET_SUCCESS = 'CHECKOUT_GET_SUCCESS';
export const CHECKOUT_GET_FAILURE = 'CHECKOUT_GET_FAILURE';

export const CHECKOUT_LOADING_STARTED = 'CHECKOUT_LOADING_STARTED';
export const CHECKOUT_LOADING_SUCCESS = 'CHECKOUT_LOADING_SUCCESS';
export const CHECKOUT_LOADING_FAILURE = 'CHECKOUT_LOADING_FAILURE';