export const INVENTORY_LOADING_STARTED = 'INVENTORY_LOADING_STARTED';
export const INVENTORY_LOADING_SUCCESS = 'INVENTORY_LOADING_SUCCESS';
export const INVENTORY_LOADING_FAILURE = 'INVENTORY_LOADING_FAILURE';