export const INVENTORY_LOADING_STARTED = 'INVENTORY_LOADING_STARTED';
export const INVENTORY_LOADING_SUCCESS = 'INVENTORY_LOADING_SUCCESS';
export const INVENTORY_LOADING_FAILURE = 'INVENTORY_LOADING_FAILURE';

export const GOODRECEIVE_LOADING_STARTED = 'GOODRECEIVE_LOADING_STARTED';
export const GOODRECEIVE_LOADING_SUCCESS = 'GOODRECEIVE_LOADING_SUCCESS';
export const GOODRECEIVE_LOADING_FAILURE = 'GOODRECEIVE_LOADING_FAILURE';
export const GOODRECEIVE_GET_STARTED = 'GOODRECEIVE_GET_STARTED';
export const GOODRECEIVE_GET_SUCCESS = 'GOODRECEIVE_GET_SUCCESS';
export const GOODRECEIVE_GET_FAILURE = 'GOODRECEIVE_GET_FAILURE';
export const GOODRECEIVE_LIST_STARTED = 'GOODRECEIVE_LIST_STARTED';
export const GOODRECEIVE_LIST_SUCCESS = 'GOODRECEIVE_LIST_SUCCESS';
export const GOODRECEIVE_LIST_FAILURE = 'GOODRECEIVE_LIST_FAILURE';
export const GOODRECEIVE_CREATE_STARTED = 'GOODRECEIVE_CREATE_STARTED';
export const GOODRECEIVE_CREATE_FAILURE = 'GOODRECEIVE_CREATE_FAILURE';
export const GOODRECEIVE_CREATE_SUCCESS = 'GOODRECEIVE_CREATE_SUCCESS';
export const GOODRECEIVE_INPUT_CHANGE = 'GOODRECEIVE_INPUT_CHANGE';