export const EMAIL_CHANGE = 'EMAIL_CHANGE';
export const NAME_SIGNUP_CHANGE = 'NAME_SIGNUP_CHANGE';
export const TEL_SIGNUP_CHANGE = 'TEL_SIGNUP_CHANGE';
export const ROLE_CHANGE = 'ROLE_CHANGE';
export const SHARE_CHANGE = 'SHARE_CHANGE';

export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const PIN_SIGNUP_CHANGE = 'PIN_SIGNUP_CHANGE';
export const PIN_CHANGE = 'PIN_CHANGE';
export const REMOVE_PIN = 'REMOVE_PIN';
export const CLEAR_PIN = 'CLEAR_PIN';

export const AUTH_LOAD_STARTED = 'AUTH_LOAD_STARTED';
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';
export const AUTH_LOAD_FAILURE = 'AUTH_LOAD_FAILURE';

export const SIGNUP_LOAD_STARTED = 'AUTH_LOAD_STARTED';
export const SIGNUP_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';
export const SIGNUP_LOAD_FAILURE = 'AUTH_LOAD_FAILURE';

export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';