export const MASTER_LOADING_STARTED = 'MASTER_LOADING_STARTED';
export const MASTER_LOADING_SUCCESS = 'MASTER_LOADING_SUCCESS';
export const MASTER_LOADING_FAILURE = 'MASTER_LOADING_FAILURE';

export const UNITOFMEASURE_LOADING_STARTED = 'UNITOFMEASURE_LOADING_STARTED';
export const UNITOFMEASURE_LOADING_SUCCESS = 'UNITOFMEASURE_LOADING_SUCCESS';
export const UNITOFMEASURE_LOADING_FAILURE = 'UNITOFMEASURE_LOADING_FAILURE';
export const UNITOFMEASURE_GET_STARTED = 'UNITOFMEASURE_GET_STARTED';
export const UNITOFMEASURE_GET_SUCCESS = 'UNITOFMEASURE_GET_SUCCESS';
export const UNITOFMEASURE_GET_FAILURE = 'UNITOFMEASURE_GETFAILURE';

export const EXPENSE_LOADING_STARTED = 'EXPENSE_LOADING_STARTED';
export const EXPENSE_LOADING_SUCCESS = 'EXPENSE_LOADING_SUCCESS';
export const EXPENSE_LOADING_FAILURE = 'EXPENSE_LOADING_FAILURE';
export const EXPENSE_GET_STARTED = 'EXPENSE_GET_STARTED';
export const EXPENSE_GET_SUCCESS = 'EXPENSE_GET_SUCCESS';
export const EXPENSE_GET_FAILURE = 'EXPENSE_GETFAILURE';

export const LOCATION_LOADING_STARTED = 'LOCATION_LOADING_STARTED';
export const LOCATION_LOADING_SUCCESS = 'LOCATION_LOADING_SUCCESS';
export const LOCATION_LOADING_FAILURE = 'LOCATION_LOADING_FAILURE';
export const LOCATION_GET_STARTED = 'LOCATION_GET_STARTED';
export const LOCATION_GET_SUCCESS = 'LOCATION_GET_SUCCESS';
export const LOCATION_GET_FAILURE = 'LOCATION_GETFAILURE';

export const PRODUCT_LOADING_STARTED = 'PRODUCT_LOADING_STARTED';
export const PRODUCT_LOADING_SUCCESS = 'PRODUCT_LOADING_SUCCESS';
export const PRODUCT_LOADING_FAILURE = 'PRODUCT_LOADING_FAILURE';
export const PRODUCT_GET_STARTED = 'PRODUCT_GET_STARTED';
export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';
export const PRODUCT_GET_FAILURE = 'PRODUCT_GET_FAILURE';
export const PRODUCT_LIST_STARTED = 'PRODUCT_LIST_STARTED';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE';
export const CREATE_LOADING_STARTED = 'CREATE_LOADING_STARTED';
export const CREATE_LOADING_FAILURE = 'CREATE_LOADING_FAILURE';
export const CREATE_LOADING_SUCCESS = 'CREATE_LOADING_SUCCESS';
export const PRODUCT_INPUT_CHANGE = 'INPUT_CHANGE';
