export const MASTER_LOADING_STARTED = 'MASTER_LOADING_STARTED';
export const MASTER_LOADING_SUCCESS = 'MASTER_LOADING_SUCCESS';
export const MASTER_LOADING_FAILURE = 'MASTER_LOADING_FAILURE';

export const UNITOFMEASURE_LOADING_STARTED = 'UNITOFMEASURE_LOADING_STARTED';
export const UNITOFMEASURE_LOADING_SUCCESS = 'UNITOFMEASURE_LOADING_SUCCESS';
export const UNITOFMEASURE_LOADING_FAILURE = 'UNITOFMEASURE_LOADING_FAILURE';
export const UNITOFMEASURE_GET_STARTED = 'UNITOFMEASURE_GET_STARTED';
export const UNITOFMEASURE_GET_SUCCESS = 'UNITOFMEASURE_GET_SUCCESS';
export const UNITOFMEASURE_GET_FAILURE = 'UNITOFMEASURE_GETFAILURE';