/**
 * Navagation Types
 */
//_SCREEN
export const BACK_PRESS = 'BACK_PRESS';
export const INVENTORY_SCREEN = 'INVENTORY_SCREEN';
export const SALERECEIVING_SCREEN = 'SALERECEIVING_SCREEN';
export const RECORD_SCREEN = 'RECORD_SCREEN';
export const TIME_SCREEN = 'TIME_SCREEN';
export const WEIGHT_SCREEN = 'WEIGHT_SCREEN';
export const SHARING_SCREEN = 'SHARING_SCREEN';
export const REPORT_SCREEN = 'REPORT_SCREEN';
export const MASTER_SCREEN = 'MASTER_SCREEN';
export const PLAN_SCREEN = 'PLAN_SCREEN';
export const PRODUCT_SCREEN = 'PRODUCT_SCREEN';
export const FORM_SCREEN = 'FORM_SCREEN';
export const MEMBER_SCREEN = 'MEMBER_SCREEN';
export const UNITOFMEASURE_SCREEN = 'UNITOFMEASURE_SCREEN';
export const LOCATION_SCREEN = 'LOCATION_SCREEN';
export const EXPENSE_SCREEN = 'EXPENSE_SCREEN';
export const GOODRECEIVE_SCREEN = 'GOODRECEIVE_SCREEN';