export const PLANTATION_LOADING_STARTED = 'PLANTATION_LOADING_STARTED';
export const PLANTATION_LOADING_SUCCESS = 'PLANTATION_LOADING_SUCCESS';
export const PLANTATION_LOADING_FAILURE = 'PLANTATION_LOADING_FAILURE';