// PRODUCT
export const PRODUCT_GET_STARTED = 'PRODUCT_GET_STARTED';
export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';
export const PRODUCT_GET_FAILURE = 'PRODUCT_GET_FAILURE';

export const PRODUCT_LOADING_STARTED = 'PRODUCT_LOADING_STARTED';
export const PRODUCT_LOADING_SUCCESS = 'PRODUCT_LOADING_SUCCESS';
export const PRODUCT_LOADING_FAILURE = 'PRODUCT_LOADING_FAILURE';