export const SALERECEIVING_LOADING_STARTED = 'SALERECEIVING_LOADING_STARTED';
export const SALERECEIVING_LOADING_SUCCESS = 'SALERECEIVING_LOADING_SUCCESS';
export const SALERECEIVING_LOADING_FAILURE = 'SALERECEIVING_LOADING_FAILURE';