export const SIGNUP_LOADING_STARTED = 'SIGNUP_LOADING_STARTED';
export const SIGNUP_LOADING_SUCCESS = 'SIGNUP_LOADING_SUCCESS';
export const SIGNUP_LOADING_FAILURE = 'SIGNUP_LOADING_FAILURE';

export const RETYPE_PASSWORD_CHECK = 'RETYPE_PASSWORD_CHECK';
export const RETYPE_PASSWORD_FAIL = 'RETYPE_PASSWORD_FAIL';
export const RETYPE_PASSWORD_SUCCESS = 'RETYPE_PASSWORD_SUCCESS';

export const EMAIL_CHANGE = 'EMAIL_CHANGE';
export const NAME_CHANGE = 'NAME_CHANGE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const RETYPE_PASSWORD_CHANGE = 'RETYPE_PASSWORD_CHANGE';
export const TEL_CHANGE = 'TEL_CHANGE';
export const ADDRESS_CHANGE = 'ADDRESS_CHANGE';






